/**
 * Milestone 6.2 — offline dialogue distillation / regeneration.
 *
 * Reads the authored situation matrix (`src/narrative/dialoguePack.json`),
 * expands role variants, and writes a committed tree JSON. Runtime play still
 * uses the TypeScript `DIALOGUE_LINES` table (ADR 0004 — no network LLM).
 *
 * Usage:
 *   pnpm exec tsx scripts/distill-dialogue.ts
 *   pnpm exec tsx scripts/distill-dialogue.ts --check   # fail if stale
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROLES = ['Pawn', 'Knight', 'Bishop', 'Rook', 'Queen', 'King'] as const;

interface DialoguePack {
  readonly version: number;
  readonly situations: Readonly<Record<string, readonly string[]>>;
}

function expandForRoles(stems: readonly string[]): readonly string[] {
  const lines: string[] = [];
  for (const role of ROLES) {
    for (const stem of stems) {
      lines.push(stem.replaceAll('{role}', role));
    }
  }
  return lines;
}

export function distillPack(pack: DialoguePack): {
  readonly version: number;
  readonly generatedAtNote: string;
  readonly situations: Record<string, readonly string[]>;
  readonly totalLines: number;
} {
  const situations: Record<string, readonly string[]> = {};
  let totalLines = 0;
  for (const [key, stems] of Object.entries(pack.situations)) {
    const lines = expandForRoles(stems);
    situations[key] = lines;
    totalLines += lines.length;
  }
  return {
    version: pack.version,
    generatedAtNote:
      'Generated by scripts/distill-dialogue.ts from dialoguePack.json. Review stems in the pack; do not hand-edit the expanded tree.',
    situations,
    totalLines,
  };
}

async function main(): Promise<void> {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  const packPath = join(root, 'src/narrative/dialoguePack.json');
  const outPath = join(root, 'src/narrative/dialogueTree.generated.json');
  const pack = JSON.parse(await readFile(packPath, 'utf8')) as DialoguePack;
  const tree = distillPack(pack);
  const serialized = `${JSON.stringify(tree, null, 2)}\n`;

  const check = process.argv.includes('--check');
  if (check) {
    const existing = await readFile(outPath, 'utf8').catch(() => '');
    if (existing !== serialized) {
      throw new Error(
        'dialogueTree.generated.json is stale; run pnpm exec tsx scripts/distill-dialogue.ts',
      );
    }
    console.log(
      `Dialogue tree up to date (${tree.totalLines} lines, ${Object.keys(tree.situations).length} situations).`,
    );
    return;
  }

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, serialized, 'utf8');
  console.log(
    `Wrote ${outPath} (${tree.totalLines} lines across ${Object.keys(tree.situations).length} situations).`,
  );
}

const isMain =
  process.argv[1] !== undefined &&
  import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/'));

if (isMain) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
